name: VCMI libtorch builds

on:
  push:
    branches:
      - lower-pytorch
  workflow_dispatch:
    inputs:
      pytorch_ref:
        description: "pytorch ref (commit SHA or tag)"
        required: true
        default: &default_ref "v2.6.0"

jobs:
  build:
    env:
      DEFAULT_REF: *default_ref
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # https://github.com/actions/runner-images/tree/main
        include:
          # - builder: windows-11-arm
          #   target: win-arm64

          # - builder: windows-2025
          #   target: win-x64

          # - builder: ubuntu-latest
          #   target: linux-x64

          # - builder: macos-15-intel
          #   target: macos-x64

          - builder: macos-15
            target: macos-arm64

          # - builder: macos-15
          #   target: ios-arm64

          # - builder: macos-15
          #   target: android-arm64

          # - builder: macos-15
          #   target: android-x64

          # 32-bit android (armeabi-v7a) builds fail with assembler error
          # (same issue as https://github.com/tensorflow/tensorflow/issues/59970)

    runs-on: ${{ matrix.builder }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout (this)
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Git config
      if: startsWith(matrix.target, 'win-')
      run: |
        git config --global core.longpaths true
        git config --global core.autocrlf true

    - name: Set PYTORCH_REF
      run: |
        set -x
        echo "PYTORCH_REF=${{ inputs.pytorch_ref || env.DEFAULT_REF }}" >> $GITHUB_ENV

    - name: Restore pytorch_src cache
      id: cache_pytorch_src
      uses: actions/cache@v4
      with:
        path: pytorch
        key: cache_pytorch_src-${{ env.PYTORCH_REF }}-${{ startsWith(matrix.target, 'win-') && 'windows' || 'default' }}

    - name: Checkout pytorch
      if: steps.cache_pytorch_src.outputs.cache-hit != 'true'
      uses: actions/checkout@v5
      with:
        submodules: recursive
        repository: pytorch/pytorch
        ref: "${{ env.PYTORCH_REF }}"
        path: pytorch

    - name: Save pytorch_src cache
      if: steps.cache_pytorch_src.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: pytorch
        key: cache_pytorch_src-${{ env.PYTORCH_REF }}-${{ startsWith(matrix.target, "win-") && "windows" || "default" }}

    - name: Set PYTORCH_SHA
      run: |
        set -x
        cd pytorch
        sha=$(git rev-parse --short=8 HEAD)
        echo "PYTORCH_SHA=$sha" >> $GITHUB_ENV

    - name: Patch
      run: |
        set -euox pipefail
        targets="generic ${{matrix.target}}"

        cd pytorch
        for t in $targets; do
          dir="patches/${{inputs.pytorch_ref}}/$t"
          [ -d "$dir" ] || continue

          for p in "$dir/"*.patch; do
            [ -r "$p" ] || continue
            git apply -v "../$p"
          done
        done

    - name: Build
      id: build
      run: |
        set -x
        export ARTIFACT_ROOT="${{github.workspace}}/artifact-root"
        mkdir -p "$ARTIFACT_ROOT"

        bash -x "scripts/${{matrix.target}}.sh"

        # # Add sha-256 to file name for traceability
        # # (GHA also shows the sha-256, but after zipping the file)
        # sha=$(openssl dgst -sha256 $OUTPUT_ARCHIVE_FILE | awk '{print $2}')
        # art=${OUTPUT_ARCHIVE_FILE/.txz/$sha.txz}
        # mv $OUTPUT_ARCHIVE_FILE $art
        # echo "artifact=$art" >> $GITHUB_OUTPUT

        echo "artifact_root=$ARTIFACT_ROOT" >> $GITHUB_OUTPUT
        echo "artifact_name=vcmi-libtorch-${{matrix.target}}-$PYTORCH_REF-$PYTORCH_SHA.zip" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{steps.build.outputs.artifact_name}}"
        path: "${{steps.build.outputs.artifact_root}}"
        compression-level: 9
        if-no-files-found: error
