name: VCMI libtorch builds

on:
  push:
    branches:
      - 2025-update
  workflow_dispatch:
    inputs:
      pytorch_ref:
        description: pytorch ref (commit SHA or tag)
        required: true
        default: "v2.8.0"  # ba56102387ef21a3b04b357e5b183d48f0afefc7
env:
  PYTORCH_REF: ${{ github.event.inputs.pytorch_ref || 'v2.8.0' }}  # on push -> 'release', on dispatch -> user input

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Info about available images:
        # https://github.com/actions/runner-images/tree/740ab068bcf1d072e2b1db63af8b77f1539dbd39?tab=readme-ov-file#available-images
        include:
          - builder: windows-2025
            target: win-x64

          # - builder: ubuntu-latest
          #   target: linux-x64

          # - builder: macos-14
          #   target: macos-x64

          # - builder: macos-14
          #   target: macos-arm64

          # - builder: macos-14
          #   target: ios-arm64

          # - builder: macos-14
          #   target: android-arm64

          # 32-bit android (armeabi-v7a) builds fail with assembler error
          # (same issue as https://github.com/tensorflow/tensorflow/issues/59970)
          #
          # mingw builds are not supported
          # (see https://stackoverflow.com/a/76160277)

    runs-on: ${{ matrix.builder }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout (this)
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Setup Rust toolchain
      if: ${{ matrix.target == 'win-x64' }}
      uses: dtolnay/rust-toolchain@stable

    - name: Download pytorch
      run: |
        set -eux
        curl -LO https://github.com/pytorch/pytorch/releases/download/${PYTORCH_REF}/pytorch-${PYTORCH_REF}.tar.gz

    - name: Build
      id: build
      env:
        INPUT_ARCHIVE_FILE: pytorch-${PYTORCH_REF}.tar.gz
        OUTPUT_ARCHIVE_FILE: libtorch-${PYTORCH_REF}-${{matrix.target}}.txz
        PYTORCH_REF: ${PYTORCH_REF}
      run: |
        bash -x "${{matrix.target}}.sh"
        echo "artifact=$OUTPUT_ARCHIVE_FILE" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{steps.build.outputs.artifact}}"
        path: "${{steps.build.outputs.artifact}}"
        compression-level: 0
        if-no-files-found: error
