name: VCMI libtorch builds

on:
  workflow_dispatch:
    inputs:
      pytorch_ref:
        description: "pytorch ref (e.g. 'v2.4.1' or a commit SHA)"
        required: true
        default: "v2.4.1"  # ee1b6804381c57161c477caa380a840a84167676

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          # - platform: mac-intel
          #   os: macos-13
          #   preset: macos-conan-ninja-release
          #   conan_profile: macos-intel
          #   conan_options: --options with_apple_system_libs=True
          #   artifact_platform: intel

          - builder: macos-14
            target: macos-arm64

          # - platform: ios
          #   os: macos-13
          #   preset: ios-release-conan-ccache
          #   conan_profile: ios-arm64
          #   conan_options: --options with_apple_system_libs=True
          # - platform: mingw
          #   os: ubuntu-22.04
          #   preset: windows-mingw-conan-linux
          #   conan_profile: mingw64-linux.jinja
          # - platform: mingw-32
          #   os: ubuntu-22.04
          #   preset: windows-mingw-conan-linux
          #   conan_profile: mingw32-linux.jinja
          # - platform: android-32
          #   os: macos-14
          #   preset: android-conan-ninja-release
          #   conan_profile: android-32-ndk
          #   conan_options: --conf tools.android:ndk_path=$ANDROID_NDK_ROOT
          #   artifact_platform: armeabi-v7a
          # - platform: android-64
          #   os: macos-14
          #   preset: android-conan-ninja-release
          #   conan_profile: android-64-ndk
          #   conan_options: --conf tools.android:ndk_path=$ANDROID_NDK_ROOT
          #   artifact_platform: arm64-v8a
    runs-on: ${{ matrix.builder }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout (this)
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download pytorch
      id: download_pytorch
      run: |
        set -eux
        curl -L https://github.com/pytorch/pytorch/releases/download/${{inputs.pytorch_ref}}/pytorch-${{inputs.pytorch_ref}}.tar.gz | tar -zx -
        echo "pytorch_dir=pytorch-${{inputs.pytorch_ref}}" >> $GITHUB_OUTPUT

    - name: Build
      id: build
      env:
        PYTORCH_DIR="${{steps.download_pytorch.outputs.pytorch_dir}}"
        ARCHIVE_FILE="libtorch-${{inputs.pytorch_ref}}-${{matrix.target}}.txz"
      run: |
        bash "${{matrix.target}}.sh"
        echo "artifact=$ARCHIVE_FILE" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{steps.build.outputs.artifact}}"
        path: "${{steps.build.outputs.artifact}}"
        compression-level: 0
        if-no-files-found: error
