name: VCMI libtorch builds

on:
  workflow_dispatch:
    inputs:
      pytorch_ref:
        description: "pytorch ref (commit SHA or tag)"
        required: true
        default: "v2.7.1"  # e2d141dbde55c2a4370fac5165b0561b6af4798b

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Info about available images:
        # https://github.com/actions/runner-images/tree/740ab068bcf1d072e2b1db63af8b77f1539dbd39?tab=readme-ov-file#available-images
        include:
          - builder: windows-2025
            target: win-x64

          - builder: ubuntu-latest
            target: linux-x64

          - builder: macos-15
            target: macos-x64

          - builder: macos-15
            target: macos-arm64

          - builder: macos-15
            target: ios-arm64

          - builder: macos-15
            target: android-arm64

          # 32-bit android (armeabi-v7a) builds fail with assembler error
          # (same issue as https://github.com/tensorflow/tensorflow/issues/59970)

    runs-on: ${{ matrix.builder }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout (this)
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Git config
      if: ${{ matrix.target == 'win-x64' }}
      run: |
        git config --global core.longpaths true
        git config --global core.autocrlf true

    - name: Checkout pytorch
      uses: actions/checkout@v5
      with:
        submodules: recursive
        repository: pytorch/pytorch
        ref: "${{ inputs.pytorch_ref }}"
        path: pytorch

    - name: Patch
      run: |
        set -euox pipefail
        targets="generic ${{matrix.target}}"

        cd pytorch
        for t in $targets; do
          dir="patches/${{inputs.pytorch_ref}}/$t"
          [ -d "$dir" ] || continue

          for p in "$dir/"*.patch; do
            [ -r "$p" ] || continue
            git apply -v "../$p"
          done
        done

    - name: Build
      id: build
      run: |
        export OUTPUT_ARCHIVE_FILE=libtorch-${{inputs.pytorch_ref}}-${{matrix.target}}.txz
        bash -x "scripts/${{matrix.target}}.sh"
        echo "artifact=$OUTPUT_ARCHIVE_FILE" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{steps.build.outputs.artifact}}"
        path: "${{steps.build.outputs.artifact}}"
        compression-level: 0
        if-no-files-found: error
